OPG_TS_data.py
OPG_powerplant_data.py

Jupyter to python for powerplant and timeslice data

---

src/osemosys_global/OPG_TS_data.py
src/osemosys_global/OPG_demand_projection.py
src/osemosys_global/OPG_file_check.py
src/osemosys_global/OPG_geographic_filter.py
src/osemosys_global/OPG_powerplant_data.py
src/osemosys_global/OPG_variablecosts.py

Added and updated the input/output file directories to the six scripts found under the src directory. Tested them all to make sure everything still runs. Had to add a "figs" folder under the "osemosys_global_model" directory to hold figures created

Relative paths

---

data/weo_2018_powerplant_costs.csv
src/osemosys_global/OPG_powerplant_data.py
src/osemosys_global/config.yaml

- Added WOF, PET, OIL, and OTH
- Set cross-border electricity trade to 0 using `TotalTechnologyModelPeriodActivityUpperLimit.csv`

Added new techs and set cross-border trade to 0

---

src/osemosys_global/snakefile

- Updated the postprocess rule shell command to use the scenario name from the config.yaml file 
- Added logging to the visualization rule

Updated paths and logging in snakefile

---

data/default_values.csv
data/operational_life.csv
src/osemosys_global/OPG_powerplant_data.py
src/osemosys_global/snakefile
src/osemosys_global/visualisation.py

- Changed OSeMOSYS file so TotalCapacityAnnual is no longer commented out 
- Updated paths and log file bug in snakefile
- Updated visualization script to read from config.yaml 
- Added operational life data to powerplant script (Issue #44 )
- Fixed bug in visualization script where it was reading all capacities (PWR, RNW, MIN) instead of just PWR ones  
- Not a change, but confirmed capacityToActivtyUnit parameter was being written correctly (Issue #57 )
- Changed default value for both variable cost and capital cost to be zero, instead of 0.0001. The model runs fine with these as zero now. (Issue #66 )

Data and Visualization Script Updates

---

workflow/scripts/osemosys_global/OPG_geographic_filter.py
workflow/scripts/osemosys_global/OPG_max_capacity.py

- Updated geographic filter to handle a list of None type. This represents a global scenario run 
- Updated the total annual max capacity logic to search through all years for the maximum residual value. The existing logic took the residual capacity in 2015 and added a capacity addition limit to it to find the total allowable capacity. However, some residual capacity values included capacity additions in years after 2015. This lead to insatiability errors. The new logic searches through all residual capacity to find the maximum to apply the capacity addition limit to

Updated filtering to handle global scenario runs

---

config/config.yaml
resources/data/color_codes.csv
workflow/scripts/osemosys_global/visualisation.py

From @maartenbrinkerink's email yesterday and our previous discussions on how to display the results... 
> When showing these results for multiple countries (or global) I suggest to group them by fuel type and not show country results separately in one graph, becomes hard to follow. Alternatively we can show results by country in separate graphs because right now the difference between India only results vs India + other countries will look minimal because of the dominance of India. 
The three changes I included in this PR are highlighted below. Then below that are figures to visually show the changes. 
1. System level results now show aggregated capacity/generation results by technology. All three plots (Capacity Annual, Generation Annual, Generation Hourly) are still generated in the …

Update Graphing Results 

---

resources/data/default_values.csv
workflow/scripts/osemosys_global/OPG_TS_data.py
workflow/scripts/osemosys_global/OPG_powerplant_data.py

1.	Updating default values for Capital Cost to 0.1 and Variable Cost to 0.001
2.	Filtering out the hydro capacity factor technologies BRA-J1, BRA-J2, BRA-J3 as Maarten confirmed these are only transmission nodes in Brazil. 
3.	Setting CSP, Wave, and Offshore Wind capacity investment to zero. This is the same solution we used with Geothermal 
#109 
TBD in data audit

General data fixes

---

CONTRIBUTING.md
README.md
config/config.yaml

Updates the `README.md` and `CONTRIBUTING.md` documents 
#110 
README.md and CONTRIBUTING.md

Updated README.md

---

workflow/scripts/osemosys_global/OPG_geographic_filter.py

Update to Geographic Trade Filtering
Updated the geographic filtering script to filter out any transmission technologies that connect to countries outside the user specified geographic scope. This is done to prevent buying of free electricity. 
#114 
Google Drive documents

Update to Geographic Trade Filtering

---

docs/modifications.md

Fixed a referencing issue in docs that broke the readthedocs build 
na
na

fix reference issue

---

workflow/scripts/osemosys_global/powerplant_data.py
workflow/scripts/osemosys_global/visualise.py

Fix the operational life of transmission lines 
na
na

update transmission oplife

---

workflow/scripts/osemosys_global/OPG_TS_data.py
workflow/scripts/osemosys_global/OPG_demand_projection.py
workflow/scripts/osemosys_global/OPG_emissions.py
workflow/scripts/osemosys_global/OPG_max_capacity.py
workflow/scripts/osemosys_global/OPG_powerplant_data.py
workflow/scripts/osemosys_global/OPG_variablecosts.py
workflow/scripts/osemosys_global/constants.py
workflow/scripts/osemosys_global/user_defined_capacity.py
workflow/scripts/osemosys_global/utils.py

Adds a constant called `SET_DTYPES` which defines the expected dtypes for each index. Before writing data, the dtypes in this constant are applied. 
Closes #153 
na

Added dtype checks when writing data

---

workflow/scripts/osemosys_global/constants.py
workflow/scripts/osemosys_global/visualise.py

Skip plotting transmission flow/capacity maps for a single region 
Closes #163 
na

Fix map plotting for no transmission

---

workflow/scripts/osemosys_global/visualisation/utils.py
workflow/scripts/osemosys_global/visualise.py

In this PR I fix the generation plots by region, and correct the color codes of regional plots.

Fix Plot By Region 

---

workflow/scripts/osemosys_global/TS_data.py
workflow/scripts/osemosys_global/emissions.py

In this PR I update logic to handle if no `EmissionLimit`, `EmissionPenalty`, or `ReserveMargin` data is added to the config file. The file shows lots of changes, but its mostly just linting. The actual changes happen in Line `660` in `TS_data.py` and at Line `74` and `86` in `emissions.py`
na
na

Fix TZ Merge Config Options

---

.gitmodules
docs/contributing.md
docs/installation.md
docs/requirements.txt
workflow/envs/osemosys-global.yaml

In this PR I have updated the Installation Instructions. Specifically I have: 
- Converted package manager to mamba 
- Fixed requirements file 
- Add GLPK and CBC to environment instead of system installs
- Update instructions to reflect this
Also, OSeMOSYS_GNU_MathProg was removed as a submodule, as nothing depends on that any more! 
Closes #180 
Installation page on read the docs

Update Install Steps and Env File 

---

setup.cfg
workflow/envs/osemosys-global.yaml
workflow/scripts/osemosys_global/demand/projection.py
workflow/snakefile

In this PR I update dependencies to be compatible with newer versions of python 
Closes #212 
na

Updates dependencies 

---

workflow/rules/retrieve.smk

Add CMO Fuel Price retrieval 

---

workflow/scripts/osemosys_global/storage/main.py
workflow/scripts/osemosys_global/summary/carbon_intensity.py
workflow/scripts/osemosys_global/summary/gen_shares.py
workflow/scripts/osemosys_global/summary/headline.py

If no storage params are defined in config, no storage is included in the mode. Empty dataframes for storage are written out. 
Closes #236 
na

Fix for runs without storage

---

workflow/scripts/osemosys_global/storage/main.py

Corrects variable scope to append the fix in #238 
na
na

Storage Hotfix

---

workflow/rules/model.smk
workflow/scripts/osemosys_global/geographic_filter.py

Updates geographic filter script to drop the dependency of the old `ConfigFile` and `ConfigPaths` classes. Uses snakemake for file management now 
na
na

Updates Geographic Filter

---

workflow/scripts/osemosys_global/powerplant/fuel_limits.py

In this PR we have addressed an error that will come up if no data is provided in the `resources/data/fuel_limits.csv` file. 
na
na

Fix for empty fuel limits

---

.github/workflows/build.yaml

Removes the testing from the github action, as it was only testing the now outdated dashboard
na
na

Corrects GitHub Action

---

docs/requirements.txt
setup.cfg

Updates `setup.cfg` to match `setuptools v78` requirements as described [here](https://setuptools.pypa.io/en/stable/history.html#bugfixes)
na
na

Corrects setup config 
